### ISSUE TITLE
Issue with headers size in C-version of the tool

### ISSUE THREAD

**Issue by vkuznet** [diana-hep/c2numpy#1]
I found empirically that if I increase headers size from O(10) level to O(100) level I get seg. fault during event generation. As we discussed with Jim it can be a problem with buffer limitation on a header or with building a list of column names. Using introduce-cpp-to-fix-column-names-bug branch the problem went away.

**Comment by jpivarski** [comment]
Fixed with that branch, and now documentation is up to date and merged into master as [revision 1.2](https://github.com/diana-hep/c2numpy/releases/tag/1.2).
